### ISSUE TITLE
Rename and additional items for the tests

### ISSUE THREAD

**Issue by humdingerb** [DarkmatterVale/Haiku-Configuration-Repo#13]
## Rename suggestions
- Device Test Form -> Desktop/Notebook Test Form
- DeviceComponent Name -> Model
- Device Display Name -> Monitor model
- Device Display Configuration -> Monitor configuration [add examples what's expected here]
- Device Graphics Card -> Graphics card/chipset
- Does the dedicated graphics card work? -> Does the graphics card/chipset work?
- Did the device work? -> Does the desktop/notebook work on a whole?

Remove the "Device" or "Component" at the beginning of the items in general and create separate pages for those two tests.
### Component Test Form
- Manufacturer
### Desktop/Notebook Test Form
- Manufactuer
- LAN Network chipset
- WLAN Network chipset
- Do the USB2.0 ports work?
- Do the USB3.0 ports work?
- Does the cardreader work?
- Does the optical drive work?

**Comment by DarkmatterVale** [comment]
@humdingerb What is a card reader? Do you mean SD card reader?

**Comment by humdingerb** [comment]
Yes, a card reader for any format, e.g. SD, CF, MMC, Memorstick and all the myriad of other formats...

**Comment by DarkmatterVale** [comment]
Just finished this
