### ISSUE TITLE
No or narrower fixed-width pages

### ISSUE THREAD

**Issue by humdingerb** [DarkmatterVale/Haiku-Configuration-Repo#14]
If the site has to be fixed width, at least make it narrower.  
Better would be something similar to the user guide which has a minimum and maximum width.

**Comment by DarkmatterVale** [comment]
It shouldn't be fixed width...If it is that is because I have used the CSS from the main Haiku website.

**Comment by DarkmatterVale** [comment]
I think I have fixed this...Please reopen if the issue persists.
