### ISSUE TITLE
Add accessory choices to component test

### ISSUE THREAD

**Issue by DarkmatterVale** [DarkmatterVale/Haiku-Configuration-Repo#20]
Currently, it is impossible to add a test for an accessory such as a keyboard or mouse. I suggest we create a third kind of test, called "accessory" to deal with accessories. @humdingerb what do you think?

**Comment by humdingerb** [comment]
Is that really necessary? What's the difference to "component"?  
I'd say everything is a "component" and "desktop/notebook" consists of a group of components.

**Comment by DarkmatterVale** [comment]
Yes after thinking about it I agree.
