### ISSUE TITLE
Don't "fail" components that were not rated by the tester

### ISSUE THREAD

**Issue by humdingerb** [DarkmatterVale/Haiku-Configuration-Repo#24]
For example, my notebook has no optical drive, so I didn't check any box for the question "Optical drive". It defaults to "Fail", where it should be "not applicable" or something. Same for "Display" or even "USB2.0" for notebooks that only have USB3.0 etc.

**Comment by DarkmatterVale** [comment]
This brings up the need for a discussion...which parts of the form should be required, and which should not?

**Comment by humdingerb** [comment]
I'd say, for the component test everything but the comment is required.  
For the system test nothing but the model, manufacturer and rating is required. If model and/or manfacturer is left empty, show a hint to enter "custom build" in case it's a desktop someone built herself.

**Comment by DarkmatterVale** [comment]
I think this has been fixed.
