### ISSUE TITLE
Component naming in Desktop/Notebook test

### ISSUE THREAD

**Issue by humdingerb** [DarkmatterVale/Haiku-Configuration-Repo#30]
Probably due to find&replace, the components in the Desktop/Notebook test are now named e.g. "Desktop/Notebook CPU". A simple "CPU" should do.

Also, maybe rename the whole test to a more generic "System test", as suggested on IRC.

**Comment by DarkmatterVale** [comment]
Thank you! I went through the site and I think I switched all of the names, but please reopen if you see an inconsistency (I will continue to check as well).
