### ISSUE TITLE
Change rating format (not 0-10)

### ISSUE THREAD

**Issue by humdingerb** [DarkmatterVale/Haiku-Configuration-Repo#31]
I find the spread of the rating from 0-10 is a bit much. What would be the difference between 1 and 2 or 7 and 8...?  
Maybe go for texty rating instead of numerical (or both). For example:
0 - "Doesn't work at all"
1 - "Works a bit" - (better than "0", but not much)
2 - "Works OK" - (works for every day tasks, but not perfectly)
3 - "Works well" - (works very well, but not every single feature is supported)
4 - "Works perfectly" - (every feature is supported)

**Comment by DarkmatterVale** [comment]
Done; thanks!
